[database]
host = "db.example.com"
port = "3306"
name = "example-db"
user = "root"
password = "secret-password"

[proxypass]
server = "lobby"

[features]
enableVoteKick = false
voteKickTimeInHours = 4