version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0

    working_directory: ~/project

    environment:
      JVM_OPTS: -Xmx8064m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run: gradle dependencies

      - save_cache:
          paths:
            - /.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      - run: gradle test
      - run:
          name: Creating artifacts
          command: gradle build
      - run: mkdir ~/workspace
      - run: cp ~/project/build/libs/* ~/workspace/
      - run: cp ~/project/tbot.yaml ~/workspace/

      - store_artifacts:
          path: ~/project/build/libs

      - persist_to_workspace:
          root: ~/workspace
          paths:
            - secure*
            - tbot*

    deploy:
      machine:
        image: ubuntu-2204:current
      steps:
        - attach_workspace:
            at: /tmp/workspace
        - run:
            name: Install Teleport
            command: |
              cd /tmp
              curl -O https://cdn.teleport.dev/teleport-v16.4.3-linux-amd64-bin.tar.gz
              tar xvf teleport-v16.4.3-linux-amd64-bin.tar.gz
              sudo ./teleport/install
        - run:
            name: Run Machine ID
            command: |
              export TELEPORT_ANONYMOUS_TELEMETRY=0
              tbot start -c /tmp/workspace/tbot.yaml
        - run:
            name: Deploy via Teleport
            command: tsh -i /tmp/workspace/machine-id/identity --proxy teleport.marylieh.social:443 scp /tmp/workspace/secure-proxy-1.0-SNAPSHOT.jar root@lxvm7-308:/mnt/denrolinc-proxy/plugins/

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          context:
            - teleport-access
          requires:
            - build
